-- ══════════════════════════════════════════════════════════════════
-- BA Elétrica — Agendamento de relatórios de Controle de Ronda
-- ══════════════════════════════════════════════════════════════════
--
-- SOLUÇÃO: GitHub Actions (MAIS CONFIÁVEL)
-- O GitHub Actions roda como scheduler EXTERNO, sem depender do banco.
-- Não há risco de pausa por inatividade.
--
-- INSTRUÇÕES:
-- 1. O arquivo .github/workflows/supabase-reports.yml já está no repo
-- 2. Ative os workflows em: https://github.com/suporte04-BA/controle-ronda/actions
-- 3. O keep-alive roda todo dia às 06:00 UTC (02:00 Manaus)
-- 4. O relatório diário roda todo dia às 06:00 UTC (02:00 Manaus)
-- 5. O relatório mensal roda no dia 1 de cada mês
--
-- ALTERNATIVA: cron-job.org (backup)
-- Se preferir um scheduler externo além do GitHub:
-- https://cron-job.org → crie 3 jobs conforme CRON_SQL_PRONTO.sql.bak
--
-- ALTERNATIVA: pg_cron (NÃO recomendado no free tier)
-- O pg_cron para quando o banco pausa (7 dias sem tráfego).
-- Só usar se o projeto tiver tráfego constante.
--
-- ══════════════════════════════════════════════════════════════════
-- VERIFICAÇÃO — Rode pra confirmar que tá tudo OK
-- ══════════════════════════════════════════════════════════════════

-- Testar a edge function (deve retornar 200)
-- GET https://rdmbayprbfqbjhfqcasp.supabase.co/functions/v1/health

-- Testar envio do relatório (deve retornar ok:true)
-- POST https://rdmbayprbfqbjhfqcasp.supabase.co/functions/v1/send-daily-report
-- Body: {"modo":"diario"}
