"$schema" = "node_modules/wrangler/config-schema.json"
name = "controle-ronda"
compatibility_date = "2026-05-20"
compatibility_flags = ["nodejs_compat"]
main = "@tanstack/react-start/server-entry"

[observability]
enabled = true
