/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AppPerfilRouteImport } from './routes/app.perfil'
import { Route as AppHistoricoRouteImport } from './routes/app.historico'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AdminSetoresRouteImport } from './routes/admin.setores'
import { Route as AdminRegistrosRouteImport } from './routes/admin.registros'
import { Route as ApiPublicCronDailyReportRouteImport } from './routes/api/public/cron.daily-report'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoricoRoute = AppHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AppRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSetoresRoute = AdminSetoresRouteImport.update({
  id: '/setores',
  path: '/setores',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRegistrosRoute = AdminRegistrosRouteImport.update({
  id: '/registros',
  path: '/registros',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicCronDailyReportRoute =
  ApiPublicCronDailyReportRouteImport.update({
    id: '/api/public/cron/daily-report',
    path: '/api/public/cron/daily-report',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/registros': typeof AdminRegistrosRoute
  '/admin/setores': typeof AdminSetoresRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/app/historico': typeof AppHistoricoRoute
  '/app/perfil': typeof AppPerfilRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/api/public/cron/daily-report': typeof ApiPublicCronDailyReportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/registros': typeof AdminRegistrosRoute
  '/admin/setores': typeof AdminSetoresRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/app/historico': typeof AppHistoricoRoute
  '/app/perfil': typeof AppPerfilRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/api/public/cron/daily-report': typeof ApiPublicCronDailyReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/registros': typeof AdminRegistrosRoute
  '/admin/setores': typeof AdminSetoresRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/app/historico': typeof AppHistoricoRoute
  '/app/perfil': typeof AppPerfilRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/api/public/cron/daily-report': typeof ApiPublicCronDailyReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/login'
    | '/admin/registros'
    | '/admin/setores'
    | '/admin/usuarios'
    | '/app/historico'
    | '/app/perfil'
    | '/admin/'
    | '/app/'
    | '/api/public/cron/daily-report'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/registros'
    | '/admin/setores'
    | '/admin/usuarios'
    | '/app/historico'
    | '/app/perfil'
    | '/admin'
    | '/app'
    | '/api/public/cron/daily-report'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/login'
    | '/admin/registros'
    | '/admin/setores'
    | '/admin/usuarios'
    | '/app/historico'
    | '/app/perfil'
    | '/admin/'
    | '/app/'
    | '/api/public/cron/daily-report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiPublicCronDailyReportRoute: typeof ApiPublicCronDailyReportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/historico': {
      id: '/app/historico'
      path: '/historico'
      fullPath: '/app/historico'
      preLoaderRoute: typeof AppHistoricoRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/setores': {
      id: '/admin/setores'
      path: '/setores'
      fullPath: '/admin/setores'
      preLoaderRoute: typeof AdminSetoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/registros': {
      id: '/admin/registros'
      path: '/registros'
      fullPath: '/admin/registros'
      preLoaderRoute: typeof AdminRegistrosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/cron/daily-report': {
      id: '/api/public/cron/daily-report'
      path: '/api/public/cron/daily-report'
      fullPath: '/api/public/cron/daily-report'
      preLoaderRoute: typeof ApiPublicCronDailyReportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminRegistrosRoute: typeof AdminRegistrosRoute
  AdminSetoresRoute: typeof AdminSetoresRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminRegistrosRoute: AdminRegistrosRoute,
  AdminSetoresRoute: AdminSetoresRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppHistoricoRoute: typeof AppHistoricoRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppHistoricoRoute: AppHistoricoRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiPublicCronDailyReportRoute: ApiPublicCronDailyReportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
