/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AppPerfilRouteImport } from './routes/app.perfil'
import { Route as AppHistoricoRouteImport } from './routes/app.historico'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AdminSetoresRouteImport } from './routes/admin.setores'
import { Route as AdminRelatorioRondaRouteImport } from './routes/admin.relatorio-ronda'
import { Route as AdminRegistrosRouteImport } from './routes/admin.registros'
import { Route as AdminObservacoesRouteImport } from './routes/admin.observacoes'
import { Route as AdminRondaDetalheIdInicioRouteImport } from './routes/admin.ronda-detalhe.$id.$inicio'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoricoRoute = AppHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AppRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSetoresRoute = AdminSetoresRouteImport.update({
  id: '/setores',
  path: '/setores',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRelatorioRondaRoute = AdminRelatorioRondaRouteImport.update({
  id: '/relatorio-ronda',
  path: '/relatorio-ronda',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRegistrosRoute = AdminRegistrosRouteImport.update({
  id: '/registros',
  path: '/registros',
  getParentRoute: () => AdminRoute,
} as any)
const AdminObservacoesRoute = AdminObservacoesRouteImport.update({
  id: '/observacoes',
  path: '/observacoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRondaDetalheIdInicioRoute =
  AdminRondaDetalheIdInicioRouteImport.update({
    id: '/ronda-detalhe/$id/$inicio',
    path: '/ronda-detalhe/$id/$inicio',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/observacoes': typeof AdminObservacoesRoute
  '/admin/registros': typeof AdminRegistrosRoute
  '/admin/relatorio-ronda': typeof AdminRelatorioRondaRoute
  '/admin/setores': typeof AdminSetoresRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/app/historico': typeof AppHistoricoRoute
  '/app/perfil': typeof AppPerfilRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/ronda-detalhe/$id/$inicio': typeof AdminRondaDetalheIdInicioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/observacoes': typeof AdminObservacoesRoute
  '/admin/registros': typeof AdminRegistrosRoute
  '/admin/relatorio-ronda': typeof AdminRelatorioRondaRoute
  '/admin/setores': typeof AdminSetoresRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/app/historico': typeof AppHistoricoRoute
  '/app/perfil': typeof AppPerfilRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/admin/ronda-detalhe/$id/$inicio': typeof AdminRondaDetalheIdInicioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/observacoes': typeof AdminObservacoesRoute
  '/admin/registros': typeof AdminRegistrosRoute
  '/admin/relatorio-ronda': typeof AdminRelatorioRondaRoute
  '/admin/setores': typeof AdminSetoresRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/app/historico': typeof AppHistoricoRoute
  '/app/perfil': typeof AppPerfilRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/ronda-detalhe/$id/$inicio': typeof AdminRondaDetalheIdInicioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/login'
    | '/admin/observacoes'
    | '/admin/registros'
    | '/admin/relatorio-ronda'
    | '/admin/setores'
    | '/admin/usuarios'
    | '/app/historico'
    | '/app/perfil'
    | '/admin/'
    | '/app/'
    | '/admin/ronda-detalhe/$id/$inicio'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/observacoes'
    | '/admin/registros'
    | '/admin/relatorio-ronda'
    | '/admin/setores'
    | '/admin/usuarios'
    | '/app/historico'
    | '/app/perfil'
    | '/admin'
    | '/app'
    | '/admin/ronda-detalhe/$id/$inicio'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/login'
    | '/admin/observacoes'
    | '/admin/registros'
    | '/admin/relatorio-ronda'
    | '/admin/setores'
    | '/admin/usuarios'
    | '/app/historico'
    | '/app/perfil'
    | '/admin/'
    | '/app/'
    | '/admin/ronda-detalhe/$id/$inicio'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/historico': {
      id: '/app/historico'
      path: '/historico'
      fullPath: '/app/historico'
      preLoaderRoute: typeof AppHistoricoRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/setores': {
      id: '/admin/setores'
      path: '/setores'
      fullPath: '/admin/setores'
      preLoaderRoute: typeof AdminSetoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/relatorio-ronda': {
      id: '/admin/relatorio-ronda'
      path: '/relatorio-ronda'
      fullPath: '/admin/relatorio-ronda'
      preLoaderRoute: typeof AdminRelatorioRondaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/registros': {
      id: '/admin/registros'
      path: '/registros'
      fullPath: '/admin/registros'
      preLoaderRoute: typeof AdminRegistrosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/observacoes': {
      id: '/admin/observacoes'
      path: '/observacoes'
      fullPath: '/admin/observacoes'
      preLoaderRoute: typeof AdminObservacoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ronda-detalhe/$id/$inicio': {
      id: '/admin/ronda-detalhe/$id/$inicio'
      path: '/ronda-detalhe/$id/$inicio'
      fullPath: '/admin/ronda-detalhe/$id/$inicio'
      preLoaderRoute: typeof AdminRondaDetalheIdInicioRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminObservacoesRoute: typeof AdminObservacoesRoute
  AdminRegistrosRoute: typeof AdminRegistrosRoute
  AdminRelatorioRondaRoute: typeof AdminRelatorioRondaRoute
  AdminSetoresRoute: typeof AdminSetoresRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminRondaDetalheIdInicioRoute: typeof AdminRondaDetalheIdInicioRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminObservacoesRoute: AdminObservacoesRoute,
  AdminRegistrosRoute: AdminRegistrosRoute,
  AdminRelatorioRondaRoute: AdminRelatorioRondaRoute,
  AdminSetoresRoute: AdminSetoresRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminRondaDetalheIdInicioRoute: AdminRondaDetalheIdInicioRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppHistoricoRoute: typeof AppHistoricoRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppHistoricoRoute: AppHistoricoRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
