/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AppPerfilRouteImport } from './routes/app.perfil'
import { Route as AppHistoricoRouteImport } from './routes/app.historico'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AdminSetoresRouteImport } from './routes/admin.setores'
import { Route as AdminRelatoriosRouteImport } from './routes/admin.relatorios'
import { Route as AdminRegistrosRouteImport } from './routes/admin.registros'
import { Route as AdminProjetosRouteImport } from './routes/admin.projetos'
import { Route as AdminLembretesRouteImport } from './routes/admin.lembretes'
import { Route as AdminChamadosRouteImport } from './routes/admin.chamados'
import { Route as AdminCategoriasRouteImport } from './routes/admin.categorias'
import { Route as AdminChamadosNovoRouteImport } from './routes/admin.chamados.novo'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoricoRoute = AppHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AppRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSetoresRoute = AdminSetoresRouteImport.update({
  id: '/setores',
  path: '/setores',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRelatoriosRoute = AdminRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRegistrosRoute = AdminRegistrosRouteImport.update({
  id: '/registros',
  path: '/registros',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjetosRoute = AdminProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLembretesRoute = AdminLembretesRouteImport.update({
  id: '/lembretes',
  path: '/lembretes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChamadosRoute = AdminChamadosRouteImport.update({
  id: '/chamados',
  path: '/chamados',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriasRoute = AdminCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChamadosNovoRoute = AdminChamadosNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AdminChamadosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/chamados': typeof AdminChamadosRouteWithChildren
  '/admin/lembretes': typeof AdminLembretesRoute
  '/admin/projetos': typeof AdminProjetosRoute
  '/admin/registros': typeof AdminRegistrosRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/setores': typeof AdminSetoresRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/app/historico': typeof AppHistoricoRoute
  '/app/perfil': typeof AppPerfilRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/chamados/novo': typeof AdminChamadosNovoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/chamados': typeof AdminChamadosRouteWithChildren
  '/admin/lembretes': typeof AdminLembretesRoute
  '/admin/projetos': typeof AdminProjetosRoute
  '/admin/registros': typeof AdminRegistrosRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/setores': typeof AdminSetoresRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/app/historico': typeof AppHistoricoRoute
  '/app/perfil': typeof AppPerfilRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/admin/chamados/novo': typeof AdminChamadosNovoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/chamados': typeof AdminChamadosRouteWithChildren
  '/admin/lembretes': typeof AdminLembretesRoute
  '/admin/projetos': typeof AdminProjetosRoute
  '/admin/registros': typeof AdminRegistrosRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/setores': typeof AdminSetoresRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/app/historico': typeof AppHistoricoRoute
  '/app/perfil': typeof AppPerfilRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/chamados/novo': typeof AdminChamadosNovoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/login'
    | '/admin/categorias'
    | '/admin/chamados'
    | '/admin/lembretes'
    | '/admin/projetos'
    | '/admin/registros'
    | '/admin/relatorios'
    | '/admin/setores'
    | '/admin/usuarios'
    | '/app/historico'
    | '/app/perfil'
    | '/admin/'
    | '/app/'
    | '/admin/chamados/novo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/categorias'
    | '/admin/chamados'
    | '/admin/lembretes'
    | '/admin/projetos'
    | '/admin/registros'
    | '/admin/relatorios'
    | '/admin/setores'
    | '/admin/usuarios'
    | '/app/historico'
    | '/app/perfil'
    | '/admin'
    | '/app'
    | '/admin/chamados/novo'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/login'
    | '/admin/categorias'
    | '/admin/chamados'
    | '/admin/lembretes'
    | '/admin/projetos'
    | '/admin/registros'
    | '/admin/relatorios'
    | '/admin/setores'
    | '/admin/usuarios'
    | '/app/historico'
    | '/app/perfil'
    | '/admin/'
    | '/app/'
    | '/admin/chamados/novo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/historico': {
      id: '/app/historico'
      path: '/historico'
      fullPath: '/app/historico'
      preLoaderRoute: typeof AppHistoricoRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/setores': {
      id: '/admin/setores'
      path: '/setores'
      fullPath: '/admin/setores'
      preLoaderRoute: typeof AdminSetoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/relatorios': {
      id: '/admin/relatorios'
      path: '/relatorios'
      fullPath: '/admin/relatorios'
      preLoaderRoute: typeof AdminRelatoriosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/registros': {
      id: '/admin/registros'
      path: '/registros'
      fullPath: '/admin/registros'
      preLoaderRoute: typeof AdminRegistrosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projetos': {
      id: '/admin/projetos'
      path: '/projetos'
      fullPath: '/admin/projetos'
      preLoaderRoute: typeof AdminProjetosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lembretes': {
      id: '/admin/lembretes'
      path: '/lembretes'
      fullPath: '/admin/lembretes'
      preLoaderRoute: typeof AdminLembretesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/chamados': {
      id: '/admin/chamados'
      path: '/chamados'
      fullPath: '/admin/chamados'
      preLoaderRoute: typeof AdminChamadosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categorias': {
      id: '/admin/categorias'
      path: '/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AdminCategoriasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/chamados/novo': {
      id: '/admin/chamados/novo'
      path: '/novo'
      fullPath: '/admin/chamados/novo'
      preLoaderRoute: typeof AdminChamadosNovoRouteImport
      parentRoute: typeof AdminChamadosRoute
    }
  }
}

interface AdminChamadosRouteChildren {
  AdminChamadosNovoRoute: typeof AdminChamadosNovoRoute
}

const AdminChamadosRouteChildren: AdminChamadosRouteChildren = {
  AdminChamadosNovoRoute: AdminChamadosNovoRoute,
}

const AdminChamadosRouteWithChildren = AdminChamadosRoute._addFileChildren(
  AdminChamadosRouteChildren,
)

interface AdminRouteChildren {
  AdminCategoriasRoute: typeof AdminCategoriasRoute
  AdminChamadosRoute: typeof AdminChamadosRouteWithChildren
  AdminLembretesRoute: typeof AdminLembretesRoute
  AdminProjetosRoute: typeof AdminProjetosRoute
  AdminRegistrosRoute: typeof AdminRegistrosRoute
  AdminRelatoriosRoute: typeof AdminRelatoriosRoute
  AdminSetoresRoute: typeof AdminSetoresRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriasRoute: AdminCategoriasRoute,
  AdminChamadosRoute: AdminChamadosRouteWithChildren,
  AdminLembretesRoute: AdminLembretesRoute,
  AdminProjetosRoute: AdminProjetosRoute,
  AdminRegistrosRoute: AdminRegistrosRoute,
  AdminRelatoriosRoute: AdminRelatoriosRoute,
  AdminSetoresRoute: AdminSetoresRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppHistoricoRoute: typeof AppHistoricoRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppHistoricoRoute: AppHistoricoRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
